// web/src/components/entity/EntityView.tsx
import { type ReactNode } from 'react';
import { EntityImage } from './EntityImage';
import { EntityDetail } from './EntityDetail';
import type { Entity } from '$/lib/api/types';

interface Props {
  entity: Entity;
  showDetails: boolean;
  toggleDetails: () => void;
  leftIcon?: ReactNode;
}

export function EntityView({ entity, showDetails, toggleDetails, leftIcon }: Props) {
  return (
    <div className="relative flex h-full flex-col md:flex-row">
      <EntityImage
        entity={entity}
        showDetails={showDetails}
        toggleDetails={toggleDetails}
        leftIcon={leftIcon}
      />
      {showDetails && <EntityDetail entity={entity} />}
    </div>
  );
}

// web/src/lib/EntityView.svelte
<script lang="ts">
  import EntityImage from './EntityImage.svelte';
  import EntityDetail from './EntityDetail.svelte';

  // Props in a single $props() call
  let { entity, showDetails = true, toggleDetails } = $props();

  $inspect(entity);
</script>

<div class="flex flex-col md:flex-row h-full relative">
  <!-- Left: Image and basic info -->
  <EntityImage 
    {entity}
    {showDetails}
    {toggleDetails}
  />
  
  <!-- Right: Details, tags, metadata -->
  {#if showDetails}
    <EntityDetail 
      {entity}
    />
  {/if}
</div>
