// web-react/src/components/entity/EntityImage.tsx
import { type ReactNode, useMemo } from 'react';
import { IndentIncrease, Library, Folder, Hash, FileClock } from 'lucide-react';
import { LucideIcon } from '$/components/common/LucideIcon';
import { translateAppName, formatDate, filename } from '$/lib/utils';
import { apiEndpoint } from '$/lib/api/client';
import type { Entity } from '$/lib/api/types';

interface Props {
  entity: Entity | null;
  showDetails: boolean;
  toggleDetails: () => void;
  leftIcon?: ReactNode;
}

function getEntityTitle(doc: Entity): string {
  const aw = doc.metadata_entries?.find((e) => e.key === 'active_window');
  if (aw) return aw.value;
  return doc.filepath ? filename(doc.filepath) : '';
}

function getAppName(doc: Entity): string {
  const aa = doc.metadata_entries?.find((e) => e.key === 'active_app');
  return aa?.value ?? 'unknown';
}

export function EntityImage({ entity, showDetails, toggleDetails, leftIcon }: Props) {
  const displayTitle = entity ? getEntityTitle(entity) : 'unknown';
  const displayAppName = entity ? getAppName(entity) : 'unknown';
  const formattedCreatedAt = useMemo(
    () => (entity?.file_created_at ? formatDate(entity.file_created_at) : ''),
    [entity?.file_created_at],
  );
  const videoUrl = entity?.filepath
    ? `${apiEndpoint}/files/video/${entity.filepath.replace(/^\/+/, '')}`
    : undefined;
  const imageUrl = entity?.filepath
    ? `${apiEndpoint}/files/${entity.filepath.replace(/^\/+/, '')}`
    : '';

  return (
    <div className={`flex h-full flex-none flex-col ${showDetails ? 'w-full md:w-1/2' : 'w-full'}`}>
      <div className="relative z-[52] mb-2">
        <div className="flex w-full items-center text-lg font-medium leading-tight text-black">
          <div className="flex w-full items-center justify-between">
            <div className="flex-none">{leftIcon}</div>
            <div className="flex min-w-0 flex-1 items-center justify-center">
              <div className="flex min-w-0 items-center space-x-2">
                <LucideIcon name={translateAppName(displayAppName) ?? 'Image'} size={24} />
                <p className="max-w-[500px] truncate">{displayTitle}</p>
                {!showDetails && formattedCreatedAt && (
                  <span className="inline-flex items-center pl-4 font-mono text-sm text-gray-500">
                    <FileClock size={16} className="mr-1 text-gray-500" />
                    {formattedCreatedAt}
                  </span>
                )}
              </div>
            </div>
            <button
              type="button"
              className="flex-none rounded-full p-2 transition-colors hover:bg-gray-100"
              onClick={toggleDetails}
              aria-label="Toggle details"
            >
              <IndentIncrease
                size={24}
                className={showDetails ? 'text-indigo-600' : 'text-gray-400'}
              />
            </button>
          </div>
        </div>
      </div>

      {showDetails && entity && (
        <div className="mb-2 mr-2 border-b border-gray-300 pb-2">
          <span className="mt-1 font-mono text-sm font-medium leading-tight text-gray-500">
            <span className="mr-4 inline-flex">
              <Library
                size={16}
                className="mr-1 text-sm font-bold uppercase tracking-wide text-indigo-600"
              />
              {entity.library_id || ''}
            </span>
            <span className="mr-4 inline-flex">
              <Folder
                size={16}
                className="mr-1 text-sm font-bold uppercase tracking-wide text-indigo-600"
              />
              {entity.folder_id || ''}
            </span>
            <span className="mr-4 inline-flex">
              <Hash
                size={16}
                className="mr-1 text-sm font-bold uppercase tracking-wide text-indigo-600"
              />
              {entity.id || ''}
            </span>
            <span className="mr-4 inline-flex">
              <FileClock
                size={16}
                className="mr-1 font-mono text-sm font-bold uppercase tracking-wide text-indigo-600"
              />
              {formattedCreatedAt}
            </span>
          </span>
          <div>
            <span className="font-xs mt-1 font-mono text-xs leading-tight text-gray-500">
              {entity.filepath || ''}
            </span>
          </div>
        </div>
      )}

      <div
        className={`relative flex flex-1 items-center justify-center overflow-hidden ${showDetails ? 'mr-2' : ''}`}
      >
        <a
          href={videoUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex h-full w-full items-center justify-center"
        >
          <img
            className="h-full rounded-lg object-contain drop-shadow-md"
            src={imageUrl}
            alt={displayTitle}
          />
        </a>
      </div>
    </div>
  );
}

// web/src/lib/EntityImage.svelte
<script lang="ts">
  import { PUBLIC_API_ENDPOINT } from '$env/static/public';
  import { IndentIncrease, Library, Folder, Hash, FileClock } from '@lucide/svelte';
  import LucideIcon from './components/LucideIcon.svelte';
  import { translateAppName, formatDate } from './utils';

  let {
    entity,
    showDetails = false,
    toggleDetails,
    LeftIcon = null,
  } = $props();

  // Compute title and app_name from entity if not explicitly provided
  let displayTitle = $derived(entity ? getEntityTitle(entity) : 'unknown');
  let displayAppName = $derived(entity ? getAppName(entity) : 'unknown');
  
  // API基础路径
  const apiEndpoint = (typeof PUBLIC_API_ENDPOINT !== 'undefined' ? PUBLIC_API_ENDPOINT : window.location.origin) + '/api';
  
  // 生成视频URL (如果路径存在)
  let videoUrl = $derived(entity?.filepath ? `${apiEndpoint}/files/video/${entity.filepath.replace(/^\/+/, '')}` : null);

  // Helper to extract the entity title from metadata_entries or fallback to filename
  function getEntityTitle(document: any): string {
    if (!document) return '';
    if (document.metadata_entries && 
      document.metadata_entries.some((entry: any) => entry.key === 'active_window')) {
      return document.metadata_entries.find((entry: any) => entry.key === 'active_window').value;
    }
    return document.filepath ? document.filepath.split('/').pop() : '';
  }

  // Helper to extract the app name from metadata_entries or fallback to 'unknown'
  function getAppName(document: any): string {
    if (!document) return 'unknown';
    if (document.metadata_entries && document.metadata_entries.some((entry: any) => entry.key === 'active_app')) {
      return document.metadata_entries.find((entry: any) => entry.key === 'active_app').value;
    } else {
      return "unknown";
    }
  }

  $inspect(entity);
</script>

<div class="flex-none {showDetails ? 'w-full md:w-1/2' : 'w-full'} flex flex-col h-full">
  <div class="mb-2 relative z-[52]">
    <div class="flex items-center text-lg leading-tight font-medium text-black w-full">
      <div class="flex items-center justify-between w-full">
        <!-- Left part - for the icon button -->
        <div class="flex-none">
          {#if LeftIcon}
            {@render LeftIcon()}
          {/if}
        </div>
        
        <!-- Center part - for the title -->
        <div class="flex-1 flex items-center justify-center min-w-0">
          <div class="flex items-center space-x-2 min-w-0">
            <LucideIcon name={translateAppName(displayAppName) || 'Image'} size={24} />
            <p class="truncate max-w-[500px]">{displayTitle}</p>
            {#if !showDetails}
            <span class="inline-flex items-center text-sm text-gray-500 font-mono pl-4">
              <FileClock size={16} class="mr-1 text-gray-500" />
              {entity?.file_created_at ? formatDate(entity.file_created_at) : ''}
            </span>
            {/if}
          </div>
        </div>
        
        <!-- Right part - for the toggle button -->
        <button
          class="p-2 hover:bg-gray-100 rounded-full transition-colors flex-none"
          onclick={toggleDetails}
        >
          <IndentIncrease 
            size={24} 
            class={showDetails ? 'text-indigo-600' : 'text-gray-400'} 
          />
        </button>
      </div>
    </div>
  </div>

  {#if showDetails}
    <div class="mb-2 mr-2 pb-2 border-b border-gray-300">
      <span class="mt-1 text-sm leading-tight font-medium text-gray-500 font-mono">
        <span class="inline-flex mr-4">
          <Library
            size={16}
            class="uppercase tracking-wide text-sm text-indigo-600 font-bold mr-1"
          />
          {entity?.library_id || ''}
        </span>

        <span class="inline-flex mr-4">
          <Folder
            size={16}
            class="uppercase tracking-wide text-sm text-indigo-600 font-bold mr-1"
          />
          {entity?.folder_id || ''}
        </span>

        <span class="inline-flex mr-4">
          <Hash
            size={16}
            class="uppercase tracking-wide text-sm text-indigo-600 font-bold mr-1"
          />
          {entity?.id || ''}
        </span>

        <span class="inline-flex mr-4">
          <FileClock
            size={16}
            class="uppercase tracking-wide text-sm text-indigo-600 font-bold mr-1 font-mono"
          />
          {entity?.file_created_at ? formatDate(entity.file_created_at) : ''}
        </span>
      </span>

      <div>
        <span class="mt-1 text-xs leading-tight font-xs text-gray-500 font-mono">
          {entity?.filepath || ''}
        </span>
      </div>
    </div>
  {/if}

  <div class="relative flex-1 overflow-hidden flex items-center justify-center {showDetails ? 'mr-2' : ''}">
    <!-- 直接使用视频链接，不需要条件判断 -->
    <a href={videoUrl} target="_blank" rel="noopener noreferrer" class="block w-full h-full flex items-center justify-center">
      <img
        class="h-full object-contain rounded-lg drop-shadow-md"
        src={entity?.image || (entity?.filepath ? `${apiEndpoint}/files/${entity.filepath.replace(/^\/+/,'')}` : '')}
        alt={displayTitle}
      />
    </a>
  </div>
</div>
