// web/src/lib/components/CopyToClipboard.svelte
<script lang="ts">
	import { Copy, Check } from '@lucide/svelte';

	let { text } = $props();

	let copied = $state(false);

	/**
	 * Copy text to clipboard and change icon
	 * @param {string} text
	 */
	function handleCopyClick(text) {
		navigator.clipboard.writeText(text).then(() => {
			copied = true;
			setTimeout(() => {
				copied = false;
			}, 2000);
		}).catch(err => {
			console.error('Failed to copy text: ', err);
		});
	}
</script>

<button class="ml-2 flex items-center" onclick={() => handleCopyClick(text)}>
	{#if copied}
		<Check size={20} />
	{:else}
		<Copy size={20} />
	{/if}
</button>

// web/src/components/common/CopyToClipboard.tsx
import { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { Button } from '$/components/ui/button';
import { toast } from 'sonner';
import { cn } from '$/lib/utils';

interface Props {
  text: string;
  className?: string;
}

export function CopyToClipboard({ text, className }: Props) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      toast.error('Failed to copy');
    }
  }

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={handleCopy}
      className={cn('h-6 w-6', className)}
    >
      {copied ? <Check size={14} /> : <Copy size={14} />}
    </Button>
  );
}
