// web/src/lib/Figure.svelte
<script>
  import { ChevronLeft, ChevronRight, X } from '@lucide/svelte';
  import { _ } from 'svelte-i18n';
  import { goto } from '$app/navigation';
  import EntityImage from './EntityImage.svelte';
  import EntityDetail from './EntityDetail.svelte';

  /**
   * @typedef {Object} Props
   * @property {string} id
   * @property {number} library_id
   * @property {number} file_created_at
   * @property {number} folder_id
   * @property {any} image
   * @property {string} filepath
   * @property {string} title
   * @property {any} app_name
   * @property {Array<string>} [tags]
   * @property {Array<{key: string, source: string, value: any}>} [metadata_entries]
   * @property {any} onClose
   * @property {any} onNext
   * @property {any} onPrevious
   */

  /** @type {Props} */
  let {
    id,
    library_id,
    file_created_at,
    folder_id,
    image,
    filepath,
    tags = [],
    metadata_entries = [],
    onClose,
    onNext,
    onPrevious
  } = $props();

  let showDetails = $state(false);

  $effect(() => {
    const savedState = localStorage.getItem('figureShowDetails');
    showDetails = savedState ? JSON.parse(savedState) : false;
  });

  function toggleDetails() {
    showDetails = !showDetails;
    localStorage.setItem('figureShowDetails', JSON.stringify(showDetails));
  }

  // English comment: This function navigates to the entity detail page.
  function goToDetail() {
    goto(`/entities/${id}`);
  }

  // Create an entity object from the props to pass to the components
  const entity = $derived({
    id,
    library_id,
    file_created_at,
    folder_id,
    image,
    filepath,
    tags,
    metadata_entries
  });

  $inspect(entity);
</script>

<div
  class="fixed inset-0 bg-gray-600 bg-opacity-50 h-full w-full z-40 flex items-center justify-center"
  id="my-modal"
>
  <div
    class="relative mx-auto border w-11/12 max-w-[95vw] h-[95vh] shadow-lg rounded-md bg-white group"
  >
    <div class="absolute inset-0 px-10 py-4">
      <!-- Button container -->
      <div class="group absolute inset-x-0 h-full">
        <button
          class="absolute p-2 left-2 top-1/2 transform -translate-y-1/2 rounded-full hover:bg-gray-100 bg-white/80 border opacity-0 group-hover:opacity-100 flex z-[51] transition-all duration-200"
          onclick={onPrevious}
        >
          <ChevronLeft size={24} class="text-indigo-600" />
        </button>
        <button
          class="absolute p-2 right-2 top-1/2 transform -translate-y-1/2 rounded-full hover:bg-gray-100 bg-white/80 border opacity-0 group-hover:opacity-100 flex z-[51] transition-all duration-200"
          onclick={onNext}
        >
          <ChevronRight size={24} class="text-indigo-600" />
        </button>
      </div>

      <div class="flex flex-col md:flex-row h-full relative">
        <!-- Image container -->
        <EntityImage {entity} {showDetails} {toggleDetails} />

        <!-- Details container -->
        {#if showDetails}
          <EntityDetail {entity} />
        {/if}
      </div>

      <div class="absolute top-2 right-2 z-[52]">
        <button
          class="p-2 rounded-full hover:bg-gray-100 bg-white/80 opacity-0 group-hover:opacity-100 transition-all duration-200"
          onclick={onClose}
        >
          <X size={24} class="text-indigo-600" />
        </button>
      </div>
      <!-- English comment: Button to view entity details page, centered at the bottom with 2em spacing -->
      <div
        class="absolute left-1/2 transform -translate-x-1/2 bottom-8 z-[53] flex justify-center w-full pointer-events-none"
      >
        <button
          class="pointer-events-auto py-2 px-4 rounded-full hover:bg-indigo-100 bg-white/80 border border-indigo-200 text-indigo-700 font-semibold transition shadow-lg text-sm"
          onclick={goToDetail}
        >
          {$_('figure.viewContext')}
        </button>
      </div>
    </div>
  </div>
</div>

// web/src/components/entity/Figure.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { ChevronLeft, ChevronRight, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { EntityImage } from './EntityImage';
import { EntityDetail } from './EntityDetail';
import type { Entity } from '$/lib/api/types';

interface Props {
  entity: Entity;
  onClose: () => void;
  onNext: () => void;
  onPrevious: () => void;
}

export function Figure({ entity, onClose, onNext, onPrevious }: Props) {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const [showDetails, setShowDetails] = useState<boolean>(() => {
    if (typeof window === 'undefined') return false;
    const saved = localStorage.getItem('figureShowDetails');
    return saved ? JSON.parse(saved) : false;
  });

  function toggleDetails() {
    setShowDetails((prev) => {
      const next = !prev;
      localStorage.setItem('figureShowDetails', JSON.stringify(next));
      return next;
    });
  }

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
      else if (e.key === 'ArrowRight') onNext();
      else if (e.key === 'ArrowLeft') onPrevious();
    }
    window.addEventListener('keydown', onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose, onNext, onPrevious]);

  function goToDetail() {
    onClose();
    void navigate({ to: '/entities/$id', params: { id: String(entity.id) } });
  }

  return (
    <div
      className="fixed inset-0 z-40 flex h-full w-full items-center justify-center bg-gray-600/50"
      id="my-modal"
    >
      <div className="group relative mx-auto h-[95vh] w-11/12 max-w-[95vw] rounded-md border bg-white shadow-lg">
        <div className="absolute inset-0 px-10 py-4">
          <button
            type="button"
            onClick={onPrevious}
            className="absolute left-2 top-1/2 z-[51] flex -translate-y-1/2 rounded-full border bg-white/80 p-2 opacity-0 transition-all duration-200 hover:bg-gray-100 group-hover:opacity-100"
            aria-label="Previous"
          >
            <ChevronLeft size={24} className="text-indigo-600" />
          </button>
          <button
            type="button"
            onClick={onNext}
            className="absolute right-2 top-1/2 z-[51] flex -translate-y-1/2 rounded-full border bg-white/80 p-2 opacity-0 transition-all duration-200 hover:bg-gray-100 group-hover:opacity-100"
            aria-label="Next"
          >
            <ChevronRight size={24} className="text-indigo-600" />
          </button>

          <div className="relative flex h-full flex-col md:flex-row">
            <EntityImage
              entity={entity}
              showDetails={showDetails}
              toggleDetails={toggleDetails}
            />
            {showDetails && <EntityDetail entity={entity} />}
          </div>

          <div className="absolute right-2 top-2 z-[52]">
            <button
              type="button"
              onClick={onClose}
              className="rounded-full bg-white/80 p-2 opacity-0 transition-all duration-200 hover:bg-gray-100 group-hover:opacity-100"
              aria-label="Close"
            >
              <X size={24} className="text-indigo-600" />
            </button>
          </div>

          <div className="pointer-events-none absolute bottom-8 left-1/2 z-[53] flex w-full -translate-x-1/2 justify-center">
            <button
              type="button"
              onClick={goToDetail}
              className="pointer-events-auto rounded-full border border-indigo-200 bg-white/80 px-4 py-2 text-sm font-semibold text-indigo-700 shadow-lg transition hover:bg-indigo-100"
            >
              {t('figure.viewContext', { defaultValue: 'View Context' })}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
